const LOAD_FILMS = 'LOAD_FILMS';
const CLEAN_FILMS = 'CLEAN_FILMS';
const CHANGE_SEARCH_VALUE = 'CHANGE_SEARCH_VALUE';
const SWITCH_LOADING_FILMS_TO_TRUE = 'SWITCH_LOADING_FILMS_TO_TRUE';
const CHANGE_CURRENT_PAGE = 'CHANGE_CURRENT_PAGE';
const LOAD_MAIN_FILM = 'LOAD_MAIN_FILM';
const GET_LATEST_FILM_ID = 'GET_LATEST_FILM_ID';
const SWITCH_ABOUT_FILM = 'SWITCH_ABOUT_FILM';
const LOAD_GENRES = 'LOAD_GENRES';
const SWITCH_ITEM_TO_INFO_MODE = 'SWITCH_ITEM_TO_INFO_MODE';
const SWITCH_ITEM_TO_MAIN_MODE = 'SWITCH_ITEM_TO_MAIN_MODE';
const OPEN_MODAL = 'OPEN_MODAL';
const CLOSE_MODAL = 'CLOSE_MODAL';
const SWITCH_TAB = 'SWITCH_TAB';

export {
  LOAD_FILMS, CLEAN_FILMS, CHANGE_SEARCH_VALUE, SWITCH_LOADING_FILMS_TO_TRUE, CHANGE_CURRENT_PAGE,
  LOAD_MAIN_FILM, GET_LATEST_FILM_ID, SWITCH_ABOUT_FILM, LOAD_GENRES, SWITCH_ITEM_TO_INFO_MODE,
  SWITCH_ITEM_TO_MAIN_MODE, OPEN_MODAL, CLOSE_MODAL, SWITCH_TAB,
};
